extends: airbnb-base
rules:
  no-console: 0
  global-require: 0
  no-restricted-syntax: 0
  no-continue: 0
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
globals:
  window: 1
  document: 1
