<!DOCTYPE html>
<html lang="en">
  <head>
    <?= partials('sn18/head') ?>
    <title>Login // Sankalan 2018</title>
    <link rel="stylesheet" href="<?= $mapAsset('sn18/common.css') ?>">
    <link rel="stylesheet" href="<?= $mapAsset('sn18/register.css') ?>">
  </head>
  <body>
    <?= partials('sn18/header', [
      'navItem' => [
        'action' => 'https://www.ducs.in/sankalan/',
        'title' => 'Main'
      ]
    ]) ?>
    <main>
      <div class="banner <?= $state['type'] ?>"><?= $state['msg'] ?></div>
      <a href="<?= $login_url ?>" class="sign-in-button button"><img src="https://unpkg.com/simple-icons@1.2.19/icons/google.svg" alt="Google">Login with Google</a>
      <p class="note"></p>
      <form class="" action="" method="post">
        <h2 style="text-align:center">Or login via your email-secret combination</h2>
        <br>
        <div class="field">
          <label for="email">Your Email</label>
          <input type="email" name="email" placeholder="Your registered Gmail ID" tabindex="0" required>
        </div>
        <div class="field">
          <label for="password">Your Secret</label>
          <input type="password" name="password" placeholder="Secret from ticket" tabindex="0" required>
        </div>
        <div class="field"><button type="submit" name="button" class="button">Login</button></div>
      </form>
    </main>
  </body>
</html>
