<!DOCTYPE html>
<html lang="en">
  <head>
    <?= partials('sn18/head') ?>
    <title>Ticket // Sankalan 2018</title>
    <link rel="stylesheet" href="<?= $mapAsset('sn18/common.css') ?>">
    <link rel="stylesheet" href="<?= $mapAsset('sn18/ticket.css') ?>"/>
  </head>
  <body>
    <?= partials('sn18/header', [
      'navItem' => [
        'action' => '/sankalan/logout',
        'title' => 'Logout'
      ]
    ]) ?>
    <main>
      <h3>Sankalan 2018 - Ticket</h3>
      <div class="row">Name: <span><?= $name ?></span></div>
      <div class="row">Email: <span><?= $email ?></span></div>
      <div class="row">Mobile: <span><?= $mobile ?></span></div>
      <div class="row">Organisation: <span><?= $org ?></span></div>
      <div class="row">Accomodation: <span><?= $accomodation === '1' ? 'TRUE' : 'FALSE' ?></span></div>
      <div class="row">&nbsp;</div>
      <div class="row" id="userid">ID: <span><?= $uid ?></span></div>
      <div class="row" title="Click masked text to toggle view secret">Secret: <span id="secret" data-text="<?= $secret ?>" data-mask="<?= $secretMask ?>"><?= $secretMask ?></span></div>
      <div class="qr" id="qrcode" data-text="sankalan-2018-user-<?= $uid ?>"></div>
      <p class="note">The information above is your identity at Sankalan. Please make sure that it is available with you during the event.
      <br>We recommend you to <strong>save this page as a screenshot</strong> on your device.
      <br>Also, please note your secret somewhere. It might be required at later stage.</p>
    </main>
    <script src="<?= $mapAsset('sn18/qrcode.min.js') ?>" charset="utf-8"></script>
    <script src="<?= $mapAsset('sn18/ticket.js') ?>" charset="utf-8"></script>
  </body>
</html>
