<!DOCTYPE html>
<html lang="en">
  <head>
    <?= partials('sn18/head') ?>
    <title>Login Admin Dashboard // Sankalan 2018</title>
    <link rel="stylesheet" href="<?= $mapAsset('sn18/common.css') ?>">
    <link rel="stylesheet" href="<?= $mapAsset('sn18/register.css') ?>">
  </head>
  <body>
    <?= partials('sn18/header', []) ?>
    <div class="banner <?= $state['type'] ?>"><?= $state['msg'] ?></div>
    <form class="" action="" method="post">
      <div class="field">
        <label for="uname">Username</label>
        <input type="text" name="uname" value="hello">
      </div>
      <div class="field">
        <label for="pass">Password</label>
        <input type="password" name="pass" value="world">
      </div>
      <div class="field">
        <button class="button" type="submit" name="button">Login</button>
      </div>
    </form>
  </body>
</html>
